Difficulty
adem-m/el_presidente pull request #28
Opened 2021-02-10 21:09 UTC by Mana-One

closes #26, closes #10

2021-02-10 21:10 UTC, Mana-One commented
added nav between main title and difficulty screen
added option to go back to a previous screen
updated Keyboard to handle integer and ENTER_KEY inputs

2021-02-11 08:16 UTC, adem-m commented
Seems great but I merge my PR first so I don't have to deal with conflicts, cheh

2021-02-11 08:17 UTC, adem-m commented
Oh, you don't have some lucky boy. Let's merge it

2021-02-11 08:20 UTC, adem-m requested changes

2021-02-11 08:20 UTC, adem-m commented on src/main/java/com/esgi/DifficultyGameMode.java
> +            index += 1;
Can be changed to `System.out.println( String.format( "%d - %s", index++, difficulty ));`
Index may have to start from 0

2021-02-14 10:51 UTC, merged